// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.pizza.domain;

import com.example.pizza.domain.PizzaIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PizzaIntegrationTest_Roo_Configurable {
    
    declare @type: PizzaIntegrationTest: @Configurable;
    
}
