// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.pizza.domain;

import com.example.pizza.domain.Base;

privileged aspect Base_Roo_JavaBean {
    
    public String Base.getName() {
        return this.name;
    }
    
    public void Base.setName(String name) {
        this.name = name;
    }
    
}
