// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.pizza.model;

import com.example.pizza.model.ColorObjectKey;
import java.io.Serializable;

privileged aspect ColorObjectKey_Roo_Serializable {
    
    declare parents: ColorObjectKey implements Serializable;
    
    private static final long ColorObjectKey.serialVersionUID = 1L;
    
}
