// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.pizza.model;

import com.example.pizza.model.ColorSwatch;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ColorSwatch_Roo_Configurable {
    
    declare @type: ColorSwatch: @Configurable;
    
}
