// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.pizza.model;

import com.example.pizza.model.ProductGroupKey;
import java.io.Serializable;

privileged aspect ProductGroupKey_Roo_Serializable {
    
    declare parents: ProductGroupKey implements Serializable;
    
    private static final long ProductGroupKey.serialVersionUID = 1L;
    
}
